// components-space/react/components/Button.jsx
import React from 'react';

function Button({ label, size, color, display = 'inline-block' }) {
  const style = {
    backgroundColor: color,
    padding: size === 'small' ? '5px 10px' : size === 'medium' ? '10px 20px' : '15px 30px',
    margin: '5px',
    border: 'none',
    borderRadius: '4px',
    color: 'white',
    fontSize: size === 'small' ? '12px' : size === 'medium' ? '14px' : '16px',
    cursor: 'pointer',
    display: display,
    boxSizing: 'border-box'
  };
  return <button style={style}>{label}</button>;
}

export default Button;

// components-space/web-components/components/button.js
if (!customElements.get('my-button')) {
  class MyButton extends HTMLElement {
    constructor() {
      super();
      const shadow = this.attachShadow({ mode: 'open' });
      const button = document.createElement('button');

      // Get the display attribute
      const display = this.getAttribute('display') || 'inline-block';

      // Apply styles to the button
      const style = document.createElement('style');
      style.textContent = `
        button {
          background-color: ${this.getAttribute('color') || '#007bff'};
          padding: ${this.getAttribute('size') === 'small' ? '5px 10px' : this.getAttribute('size') === 'medium' ? '10px 20px' : '15px 30px'};
          margin: 5px;
          border: none;
          border-radius: 4px;
          color: white;
          font-size: ${this.getAttribute('size') === 'small' ? '12px' : this.getAttribute('size') === 'medium' ? '14px' : '16px'};
          cursor: pointer;
          display: ${display};
          box-sizing: border-box;
        }
      `;
      shadow.appendChild(style);
      button.textContent = this.getAttribute('label');
      shadow.appendChild(button);
    }
  }

  customElements.define('my-button', MyButton);
}
